[tool.poetry]
name = "pythonproject1"
version = "0.1.0"
description = ""
authors = ["maksy <maksykaryak@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

